### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Serph91P** [ChaoticByte/GronkhTV-Downloader#3]
Wäre schön wenn du die einfügen könntest um es einfach zu installieren. So muss man sich erst alle dependencies raussuchen ;)

**Comment by Serph91P** [comment]
> Wäre schön wenn du die einfügen könntest um es einfach zu installieren. So muss man sich erst alle dependencies raussuchen ;)

ok scheint keine abhängikeit zu sein sondern ein fehler mit dem script anich:

```
python3 gtv-dl.py 768
================================================================================================================================================================================
GTV0768, 2023-10-18 - Nächster Stream vsl. Mittwoch. Bis dahin 🍁 247 auf @GronkhTV 🍂 !comic !archiv
================================================================================================================================================================================
Downloading to "GTV0768, 2023-10-18 - Nächster Stream vsl. Mittwoch. Bis dahin 🍁 247 auf @GronkhTV 🍂 !comic !archiv.ts"
Format: 720p
================================================================================================================================================================================
02.46%Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1451, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxe/Downloads/gtv-dl.py", line 302, in <module>
    v.download(args.download_to, args.format, args.start, args.stop, args.overwrite)
  File "/home/maxe/Downloads/gtv-dl.py", line 246, in download
    for c in video_stream.download_chunks(start + current_dl_offset, stop):
  File "/home/maxe/Downloads/gtv-dl.py", line 119, in download_chunks
    yield request_get(self.baseurl + c, self._CDN_HEADERS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxe/Downloads/gtv-dl.py", line 24, in request_get
    with _request.urlopen(req) as resp:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
